package POJOS;
// Generated 20-abr-2024 16:27:40 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * Lineasrecibo generated by hbm2java
 */
public class Lineasrecibo  implements java.io.Serializable {


     private int id;
     private Lecturas lecturas;
     private String concepto;
     private String subconcepto;
     private BigDecimal baseImponible;
     private BigDecimal porcentajeIva;
     private BigDecimal importeiva;
     private int m3incluidos;
     private BigDecimal bonificacion;
     private BigDecimal importeBonificacion;

    public Lineasrecibo() {
    }

	
    public Lineasrecibo(int id, String concepto, String subconcepto, BigDecimal baseImponible, BigDecimal porcentajeIva, BigDecimal importeiva, int m3incluidos, BigDecimal bonificacion) {
        this.id = id;
        this.concepto = concepto;
        this.subconcepto = subconcepto;
        this.baseImponible = baseImponible;
        this.porcentajeIva = porcentajeIva;
        this.importeiva = importeiva;
        this.m3incluidos = m3incluidos;
        this.bonificacion = bonificacion;
    }
    public Lineasrecibo(int id, Lecturas lecturas, String concepto, String subconcepto, BigDecimal baseImponible, BigDecimal porcentajeIva, BigDecimal importeiva, int m3incluidos, BigDecimal bonificacion, BigDecimal importeBonificacion) {
       this.id = id;
       this.lecturas = lecturas;
       this.concepto = concepto;
       this.subconcepto = subconcepto;
       this.baseImponible = baseImponible;
       this.porcentajeIva = porcentajeIva;
       this.importeiva = importeiva;
       this.m3incluidos = m3incluidos;
       this.bonificacion = bonificacion;
       this.importeBonificacion = importeBonificacion;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Lecturas getLecturas() {
        return this.lecturas;
    }
    
    public void setLecturas(Lecturas lecturas) {
        this.lecturas = lecturas;
    }
    public String getConcepto() {
        return this.concepto;
    }
    
    public void setConcepto(String concepto) {
        this.concepto = concepto;
    }
    public String getSubconcepto() {
        return this.subconcepto;
    }
    
    public void setSubconcepto(String subconcepto) {
        this.subconcepto = subconcepto;
    }
    public BigDecimal getBaseImponible() {
        return this.baseImponible;
    }
    
    public void setBaseImponible(BigDecimal baseImponible) {
        this.baseImponible = baseImponible;
    }
    public BigDecimal getPorcentajeIva() {
        return this.porcentajeIva;
    }
    
    public void setPorcentajeIva(BigDecimal porcentajeIva) {
        this.porcentajeIva = porcentajeIva;
    }
    public BigDecimal getImporteiva() {
        return this.importeiva;
    }
    
    public void setImporteiva(BigDecimal importeiva) {
        this.importeiva = importeiva;
    }
    public int getM3incluidos() {
        return this.m3incluidos;
    }
    
    public void setM3incluidos(int m3incluidos) {
        this.m3incluidos = m3incluidos;
    }
    public BigDecimal getBonificacion() {
        return this.bonificacion;
    }
    
    public void setBonificacion(BigDecimal bonificacion) {
        this.bonificacion = bonificacion;
    }
    public BigDecimal getImporteBonificacion() {
        return this.importeBonificacion;
    }
    
    public void setImporteBonificacion(BigDecimal importeBonificacion) {
        this.importeBonificacion = importeBonificacion;
    }




}


