package POJOS;
// Generated 20-abr-2024 16:27:40 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Ordenanza generated by hbm2java
 */
public class Ordenanza  implements java.io.Serializable {


     private int id;
     private int idOrdenanza;
     private String concepto;
     private String subconcepto;
     private String descripcion;
     private String acumulable;
     private BigDecimal precioFijo;
     private int m3incluidos;
     private BigDecimal preciom3;
     private BigDecimal porcentaje;
     private String conceptoRelacionado;
     private BigDecimal iva;
     private String pueblo;
     private String tipoCalculo;
     private Set relContribuyenteOrdenanzas = new HashSet(0);

    public Ordenanza() {
    }

	
    public Ordenanza(int id, int idOrdenanza, String concepto, String subconcepto, String descripcion, String acumulable, BigDecimal precioFijo, int m3incluidos, BigDecimal iva, String pueblo, String tipoCalculo) {
        this.id = id;
        this.idOrdenanza = idOrdenanza;
        this.concepto = concepto;
        this.subconcepto = subconcepto;
        this.descripcion = descripcion;
        this.acumulable = acumulable;
        this.precioFijo = precioFijo;
        this.m3incluidos = m3incluidos;
        this.iva = iva;
        this.pueblo = pueblo;
        this.tipoCalculo = tipoCalculo;
    }
    public Ordenanza(int id, int idOrdenanza, String concepto, String subconcepto, String descripcion, String acumulable, BigDecimal precioFijo, int m3incluidos, BigDecimal preciom3, BigDecimal porcentaje, String conceptoRelacionado, BigDecimal iva, String pueblo, String tipoCalculo, Set relContribuyenteOrdenanzas) {
       this.id = id;
       this.idOrdenanza = idOrdenanza;
       this.concepto = concepto;
       this.subconcepto = subconcepto;
       this.descripcion = descripcion;
       this.acumulable = acumulable;
       this.precioFijo = precioFijo;
       this.m3incluidos = m3incluidos;
       this.preciom3 = preciom3;
       this.porcentaje = porcentaje;
       this.conceptoRelacionado = conceptoRelacionado;
       this.iva = iva;
       this.pueblo = pueblo;
       this.tipoCalculo = tipoCalculo;
       this.relContribuyenteOrdenanzas = relContribuyenteOrdenanzas;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public int getIdOrdenanza() {
        return this.idOrdenanza;
    }
    
    public void setIdOrdenanza(int idOrdenanza) {
        this.idOrdenanza = idOrdenanza;
    }
    public String getConcepto() {
        return this.concepto;
    }
    
    public void setConcepto(String concepto) {
        this.concepto = concepto;
    }
    public String getSubconcepto() {
        return this.subconcepto;
    }
    
    public void setSubconcepto(String subconcepto) {
        this.subconcepto = subconcepto;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getAcumulable() {
        return this.acumulable;
    }
    
    public void setAcumulable(String acumulable) {
        this.acumulable = acumulable;
    }
    public BigDecimal getPrecioFijo() {
        return this.precioFijo;
    }
    
    public void setPrecioFijo(BigDecimal precioFijo) {
        this.precioFijo = precioFijo;
    }
    public int getM3incluidos() {
        return this.m3incluidos;
    }
    
    public void setM3incluidos(int m3incluidos) {
        this.m3incluidos = m3incluidos;
    }
    public BigDecimal getPreciom3() {
        return this.preciom3;
    }
    
    public void setPreciom3(BigDecimal preciom3) {
        this.preciom3 = preciom3;
    }
    public BigDecimal getPorcentaje() {
        return this.porcentaje;
    }
    
    public void setPorcentaje(BigDecimal porcentaje) {
        this.porcentaje = porcentaje;
    }
    public String getConceptoRelacionado() {
        return this.conceptoRelacionado;
    }
    
    public void setConceptoRelacionado(String conceptoRelacionado) {
        this.conceptoRelacionado = conceptoRelacionado;
    }
    public BigDecimal getIva() {
        return this.iva;
    }
    
    public void setIva(BigDecimal iva) {
        this.iva = iva;
    }
    public String getPueblo() {
        return this.pueblo;
    }
    
    public void setPueblo(String pueblo) {
        this.pueblo = pueblo;
    }
    public String getTipoCalculo() {
        return this.tipoCalculo;
    }
    
    public void setTipoCalculo(String tipoCalculo) {
        this.tipoCalculo = tipoCalculo;
    }
    public Set getRelContribuyenteOrdenanzas() {
        return this.relContribuyenteOrdenanzas;
    }
    
    public void setRelContribuyenteOrdenanzas(Set relContribuyenteOrdenanzas) {
        this.relContribuyenteOrdenanzas = relContribuyenteOrdenanzas;
    }




}


